language: c
sudo: false

services:
  - redis-server

env:
  global:
    - PATH=$HOME/.crenv/bin:$PATH
  matrix:
    - CRYSTAL_VERSION=0.10.0
    - CRYSTAL_VERSION=0.10.1

install:
  - curl -L https://raw.github.com/pine613/crenv/master/install.sh | bash
  - eval "$(crenv init -)"
  - crenv install $CRYSTAL_VERSION
  - crenv global $CRYSTAL_VERSION
  - crystal --version

before_script:
  - crystal deps

script:
  - crystal spec -v

notifications:
  slack:
    - secure: "BuV82y9qiN9/E2hA8md311fMd9lr9wWszfbpw046EIlgepd0GUBny0BZOFGaAxOMp4ScsOek1Zsvzf99PVISKj6EsEkUd+X6eIMiHNaARshFeT6ZmB+DTUCoNKz2XFVu78hkxefk4/0CLfo9LTezHEU54Eige8JiO0VQRjxMkdWMAs7Qq0zAfbyFxexxGzHVvZBNn+tclWXea45C/FCEwcqJ3hLMspqqxNw067OLyH18ujH9EUdc+HtvJJ89wzfTt8zoGprSG2KNKaAerevoYfYMmKes8DWqLDVfqoaHvL5kdtBGGUV8nsTh39Lsm4NgFzabKPMZaUV4UH5mYrsSOPEX/ECbgyP9D3+e/PMHzKRysqejriFuaiKgGP8sCdst7M9Byo4BzvxE23/bc368h/mJnONzTUQUd4XFYX7pCDf2NZHp05vL8oh6jpIUl4Odo1r9pv6nmgAfW0bcJWYZzmyGF4QF2pMXrMwe7Igj94G7OiUyBoc3lng3GX5qSOIfw03ga8xFNYqunsPhvOWm8qVqJgiRRreI4NWDdGaDPdQrooeyXwUXsln/ZIcrcwaR8nc4JgbQ0Fv8CeFpbw+1ywIJmPo2kuMkefsabADAKbo3T8UvH1UCgm6iDfg+AeqCWC6F97np5nWIugJHAdoexunJBiTCtMP/QpotmHIP+kw="
